version: '3.3'

services:
  redis:
    image: redis:latest
    container_name: redis-secure
    ports:
     - "6379:6379"  # Expose Redis seulement si nÃ©cessaire
    networks:
      - redis
    volumes:
      - ./redis-data:/data  
      - ./redis.conf:/usr/local/etc/redis/redis.conf  
      - ./certs:/certs  
      - /etc/localtime:/etc/localtime:ro 
      - ./redis-log:/var/log/redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD} 
    command: >
      redis-server /usr/local/etc/redis/redis.conf 
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "15m"  
        max-file: "1"     
    tty: true

networks:
  redis:
    driver: bridge